version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
      dev-dependencies:
        dependency-type: development
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      dev-dependencies-major:
        dependency-type: development
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: cargo
    directory: /crates/engine
    schedule:
      interval: monthly
    groups:
      cargo:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
